version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "8000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
